export const FETCH_FAVOURITES_REQUEST = 'FETCH_FAVOURITES_REQUEST'
export const FETCH_FAVOURITES_SUCCESS = 'FETCH_FAVOURITES_SUCCESS'
export const POST_FAVOURITE_BREED_REQUEST = 'POST_FAVOURITE_BREED_REQUEST'
export const POST_FAVOURITE_BREED_SUCCESS = 'POST_FAVOURITE_BREED_SUCCESS'